# I have modified this file! But it was previously a 'hardware-configuration' generated by ‘nixos-generate-config’
{
  den.aspects.boot.nixos = { pkgs, modulesPath, ... }: {
    imports = [ 
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    # Set bootloader options (specific to hardware)
    boot.loader = {
      efi.canTouchEfiVariables = true;
      efi.efiSysMountPoint = "/boot";
      systemd-boot.enable = true; # todo: work with grub or other bootloader
    };

    # Use latest Linux kernel
    boot.kernelPackages = pkgs.linuxPackages_latest;
    # boot.tmp.cleanOnBoot = true; # Clear /tmp on boot  Necessary? We delete / anyways...

    # todo: research boot.binfmt.emulatedSystems and preferStaticEmulators and its performance in emulation

    boot.supportedFilesystems = [ # Specify which removable media we can read
      "ext4"
      "btrfs"
      "ntfs"
      "fat"
      "vfat"
      "exfat"
    ];

    boot.initrd = {
      # Unlock the primary LUKS device with a passphrase
      luks.devices."crypt" = { # todo: work with yubikey or keyfile
        # allowDiscards = true  todo: see if this prevents async discards (which we flag many times below)
        bypassWorkqueues = true;
      };
    };
  };
}
