# I have modified this file! But it was previously a 'hardware-configuration' generated by ‘nixos-generate-config’
{
  config,
  lib,
  pkgs, 
  modulesPath,
  ...
}:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Set bootloader options (specific to hardware)
  boot.loader = {
    efi.canTouchEfiVariables = true;
    efi.efiSysMountPoint = "/boot";
    systemd-boot.enable = true; # todo: work with grub or other bootloader
  };

  # Use latest Linux kernel
  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.tmp.cleanOnBoot = true; # Clear /tmp on boot

  # todo: research boot.binfmt.emulatedSystems and preferStaticEmulators and its performance in emulation

  boot.supportedFilesystems = [ # Specify which removable media we can read
    "ext4"
    "btrfs"
    "ntfs"
    "fat"
    "vfat"
    "exfat"
  ];

  boot.initrd = {
    # Unlock the primary LUKS device with a passphrase
    luks.devices."crypt" = { # todo: work with yubikey or keyfile
      # allowDiscards = true  todo: see if this prevents async discards (which we flag many times below)
      bypassWorkqueues = true;
    };
  };

  # We can access all of BTRFS' subvolumes from /pool
  fileSystems."/pool" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ "subvolid=5" ]; # The ID used for the BTRFS subvolume pool
  };

  # Root filesystem
  fileSystems."/" = {
    device = "tmpfs"; # Erase your darlings!
    fsType = "tmpfs";
    options = [
      "relatime"
      "mode=755" # systemd defaults to 777, which sometimes causes problems
    ];
  };

  # Nix store
  fileSystems."/nix" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ 
      "subvol=@nix"
      "compress-force=zstd:1" # Force level 1 ZSTD compression on all files; quickest, most bang-for-buck
      "relatime"              # Write access time relative to it's creation/modification time
      "discard=async"         # Asynchronus discard; free up deleted blocks in chunks
      "space_cache=v2"        # Use a new and faster btrfs space cache
      "ssd"                   # Specify this mount is on an SSD
    ];
  };

  # Temporary directory; cleared on boot
  fileSystems."/tmp" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ 
      "subvol=@tmp"
      "compress-force=zstd:1"
      "relatime"
      "discard=async"
      "space_cache=v2"
      "ssd"
    ];
  };

  # Contains all our logs (/var/log symlinks here)
  fileSystems."/log" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ 
      "subvol=@log"
      "compress-force=zstd:1"
      "discard=async"
      "space_cache=v2"
      "ssd"
    ];
  };

  # Home directory
  # fileSystems."/home" = {
  #   device = "/dev/mapper/crypt";
  #  fsType = "btrfs";
  #   options = [ 
  #     "subvol=@home"
  #     "compress-force=zstd:1"
  #     "relatime"
  #     "discard=async"
  #     "space_cache=v2"
  #     "ssd"
  #   ];
  # };

  # Persistent directory; pats of our root that need to persist between boots
  fileSystems."/persist" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ 
      "subvol=@persist"
      "compress-force=zstd:1"
      "relatime"
      "discard=async"
      "space_cache=v2"
      "ssd"
    ];
    neededForBoot = true;
  };

  # Holds our BTRFS snapshots
  fileSystems."/snapshots" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ 
      "subvol=@snapshots"
      "compress-force=zstd:1"
      "relatime"
      "discard=async"
      "space_cache=v2"
      "ssd"
    ];
  };

  # The location of our swapfile (read only)
  fileSystems."/swap" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = [ 
      "subvol=@swap"
      "space_cache=v2"
      "ssd"
      "ro"
    ];
  };

  # Our swapfile itself (read/write)
  fileSystems."/swap/swapfile" = {
    depends = [ "/swap" ];
    device = "/swap/swapfile";
    fsType = "none";
    options = [
      "bind" # Bind means we're mounting this directory within another directory
      "rw"
    ];
  };

  swapDevices = [ # Point Nix in the direction of our swapfile, which is not a separate partition; hence the curly brackets
    { device = "/swap/swapfile"; }
  ];

  # Our boot device
  fileSystems."/boot" = {
    fsType = "vfat";
    options = [ 
      "fmask=0177" # File mask:      Owner rw-, Group/Others ---
      "dmask=0077" # Directory mask: Owner rwx, Group/Others ---
      "noexec,nosuid,nodev" # Block execution, ignore setuid, and disable device nodes
    ];
  };

  # Enable DHCP on device interfaces, both wired and wireless. Hardware specific
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
